name: gitleaks-scan

on:
  push:
    branches:
      - main
      - develop
jobs:
  build:
    name: Gitleaks-Scan
    runs-on: ubuntu-latest
    env:
      JENKINS_JOB:  https://227e-122-171-16-219.ngrok.io/job/gitleaks-pipeline-demo/
    steps:
    - name: Trigger Job
      run: |
        curl $JENKINS_JOB --header "Authorization: Basic bmloYWw6MTFlNzZmMTAwYWU4NzY1ZjU0MzdkNTQyNzVkMGQ3NWVjZQo="
    -  name: Branch Name
       run: echo running on branch ${{ github.head_ref || github.ref_name }} 
