name: gitleaks-scan

on:
  push:
    branches:
      - main
      - develop
jobs:
  build:
    name: Gitleaks-Scan
    runs-on: ubuntu-latest
    env:
      JENKINS_JOB:  https://691e-122-171-16-219.ngrok.io/job/gitleaks-pipeline-demo/buildWithParameters?branchName=${{ github.head_ref || github.ref_name }}&repoName=${{ github.event.repository.name }}
    steps:
    - name: Trigger Job
      run: |
        curl -X POST $JENKINS_JOB --header "Authorization: Basic bmloYWw6MTFlNzZmMTAwYWU4NzY1ZjU0MzdkNTQyNzVkMGQ3NWVjZQ"
    -  name: Branch Name
       run: echo running on branch ${{ github.head_ref || github.ref_name }}
    -  name: Repo Name
       run: echo Repo Name ${{ github.event.repository.name }}
